#!/bin/bash

# Setting up some environment variables
export TMP_FOLDER="tmp"
export SCRIPTS_FOLDER="scripts"
export FILES_FOLDER="files"

export firefox_file="firefox.tar.bz2"
export atom_file="atom.deb"

if ((`uname -m` == "x86_64")); then
        ARCHITETURE="64";
else
        ARCHITETURE="32";
fi

export ARCHITETURE

# Enable log files
exec 2> .log

echo "=================================="
echo "If an error occurs, check the '.log' file!"
echo "=================================="

# First, update the system
echo "System update"
yes | sudo apt-get update &>> .log
yes | sudo apt-get upgrade &>> .log

# Basics and acessories
yes | ./scripts/acessories.sh

# Webdev tools
read -p "Do you wish to install webdev tools [Apache, phpMyAdmin, MySQL] (y/n)?" answer
case $answer in
    [Yy]* ) yes | ./scripts/tools.sh; break;;
    [Nn]* ) exit;;
    * ) echo "Please answer yes or no.";;
esac

echo "That's it!"
